name: Docker Build and Tag

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Code auschecken
        uses: actions/checkout@v3

      - name: Docker Image bauen
        run: docker build -t cocreate-docker-app .

      # Optional: Container testweise starten und prüfen, ob er läuft
      - name: Testweise starten und prüfen
        run: |
          docker run -d -p 8080:8080 --name test-app cocreate-docker-app
          sleep 5
          curl -sSf http://localhost:8080 || (echo "Start fehlgeschlagen" && exit 1)
          docker stop test-app
          docker rm test-app

      - name: Git Tag setzen
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag auto-deploy-$(date +'%Y%m%d%H%M%S')
          git push --tags
